/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentTraceRouteImport } from './routes/agent-trace'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EvalLabRouteImport } from './routes/eval-lab'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as VerifyRouteImport } from './routes/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentTraceRoute = AgentTraceRouteImport.update({
  id: '/agent-trace',
  path: '/agent-trace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalLabRoute = EvalLabRouteImport.update({
  id: '/eval-lab',
  path: '/eval-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-trace': typeof AgentTraceRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/eval-lab': typeof EvalLabRoute
  '/exceptions': typeof ExceptionsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-trace': typeof AgentTraceRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/eval-lab': typeof EvalLabRoute
  '/exceptions': typeof ExceptionsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-trace': typeof AgentTraceRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/eval-lab': typeof EvalLabRoute
  '/exceptions': typeof ExceptionsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-trace'
    | '/auth'
    | '/dashboard'
    | '/eval-lab'
    | '/exceptions'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-trace'
    | '/auth'
    | '/dashboard'
    | '/eval-lab'
    | '/exceptions'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/agent-trace'
    | '/auth'
    | '/dashboard'
    | '/eval-lab'
    | '/exceptions'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentTraceRoute: typeof AgentTraceRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  EvalLabRoute: typeof EvalLabRoute
  ExceptionsRoute: typeof ExceptionsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-trace': {
      id: '/agent-trace'
      path: '/agent-trace'
      fullPath: '/agent-trace'
      preLoaderRoute: typeof AgentTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval-lab': {
      id: '/eval-lab'
      path: '/eval-lab'
      fullPath: '/eval-lab'
      preLoaderRoute: typeof EvalLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentTraceRoute: AgentTraceRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  EvalLabRoute: EvalLabRoute,
  ExceptionsRoute: ExceptionsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
