"""Tests for dataset generation, truth partitioning, journals, and seeds (I3, I5, D3, R3)."""

import hashlib
import re

from engine.core.generator.build import generate_dataset
from engine.core.models import ExceptionBucket


def _dataset_hash(dataset: object) -> str:
    """Compute a deterministic hash across all generated records."""
    serialized = dataset.to_json()  # type: ignore[attr-defined]
    return hashlib.sha256(serialized.encode("utf-8")).hexdigest()


def test_seed_stability() -> None:
    """Two runs at seed=42 give identical SHA256 for all sources."""
    d1 = generate_dataset(n=100, seed=42)
    d2 = generate_dataset(n=100, seed=42)

    assert _dataset_hash(d1) == _dataset_hash(d2)
    assert len(d1.bank_txns) == len(d2.bank_txns)
    assert len(d1.gateway_payouts) == len(d2.gateway_payouts)
    assert len(d1.ledger_entries) == len(d2.ledger_entries)
    assert len(d1.truth_groups) == len(d2.truth_groups)


def test_cross_seed_variance() -> None:
    """Seeds 1..20 give 20 distinct SHA256 values."""
    hashes = set()
    for seed in range(1, 21):
        d = generate_dataset(n=60, seed=seed)
        h = _dataset_hash(d)
        hashes.add(h)
    assert len(hashes) == 20


def test_truth_partition() -> None:
    """I5 — truth partitions all row IDs without overlaps or unassigned rows."""
    dataset = generate_dataset(n=100, seed=42)

    bank_ids_in_groups: list[str] = []
    payout_ids_in_groups: list[str] = []
    ledger_ids_in_groups: list[str] = []

    for group in dataset.truth_groups:
        bank_ids_in_groups.extend(group.bank_ids)
        payout_ids_in_groups.extend(group.payout_ids)
        ledger_ids_in_groups.extend(group.ledger_ids)

    # Check that each ID in source appears exactly once in truth groups
    source_bank_ids = [b.bank_id for b in dataset.bank_txns]
    source_payout_ids = [p.payout_id for p in dataset.gateway_payouts]
    source_ledger_ids = [entry.ledger_id for entry in dataset.ledger_entries]

    assert sorted(bank_ids_in_groups) == sorted(source_bank_ids)
    assert len(bank_ids_in_groups) == len(set(bank_ids_in_groups))

    assert sorted(payout_ids_in_groups) == sorted(source_payout_ids)
    assert len(payout_ids_in_groups) == len(set(payout_ids_in_groups))

    assert sorted(ledger_ids_in_groups) == sorted(source_ledger_ids)
    assert len(ledger_ids_in_groups) == len(set(ledger_ids_in_groups))


def test_journals_balance() -> None:
    """I3 — every journal set sums to 0 (D3)."""
    dataset = generate_dataset(n=100, seed=42)

    # Group ledger entries by journal_id
    journals: dict[str, list[int]] = {}
    for entry in dataset.ledger_entries:
        journals.setdefault(entry.journal_id, []).append(entry.amount_paise)

    assert len(journals) > 0
    for journal_id, amounts in journals.items():
        assert sum(amounts) == 0, f"Journal {journal_id} does not balance: sum={sum(amounts)}"


def test_no_real_utrs() -> None:
    """All UTRs SYNTH-prefixed; real-bank regexes match nothing."""
    dataset = generate_dataset(n=100, seed=42)

    real_bank_utr_patterns = [
        re.compile(r"^[A-Z]{4}\d{16}$"),  # HDFC/ICICI standard 20-22 char formats
        re.compile(r"^CMS\d+$"),
        re.compile(r"^AXIS\d+$"),
        re.compile(r"^SBIN\d+$"),
    ]

    for b in dataset.bank_txns:
        if b.utr is not None:
            assert b.utr.startswith("SYNTH"), f"Non-synthetic bank UTR: {b.utr}"
            for pat in real_bank_utr_patterns:
                assert not pat.match(b.utr), f"Matched real bank pattern: {b.utr}"

    for p in dataset.gateway_payouts:
        if p.utr is not None:
            assert p.utr.startswith("SYNTH"), f"Non-synthetic payout UTR: {p.utr}"
            for pat in real_bank_utr_patterns:
                assert not pat.match(p.utr), f"Matched real bank pattern: {p.utr}"


def test_bucket_generators() -> None:
    """Each of the 9 unresolved buckets (except partial_group) has >= 1 generating cohort."""
    dataset = generate_dataset(n=100, seed=42)

    buckets_present = {
        g.expected_bucket for g in dataset.truth_groups if g.expected_bucket is not None
    }

    expected_generator_buckets = {
        ExceptionBucket.AMOUNT_MISMATCH,
        ExceptionBucket.FEE_MISMATCH,
        ExceptionBucket.TIMING_BREAK,
        ExceptionBucket.MISSING_UTR,
        ExceptionBucket.DUPLICATE,
        ExceptionBucket.REFUND_UNPAIRED,
        ExceptionBucket.ORPHAN_BANK,
        ExceptionBucket.ORPHAN_LEDGER,
    }

    # partial_group is not generated by a cohort (it only catches pipeline/matching errors)
    assert expected_generator_buckets.issubset(buckets_present)
