/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SeedSet = "dev" | "holdout" | "regression";
export type MeasurementMode = "live" | "replay";

/**
 * Track 04 AI Finance Controller — report contract. Frozen at P0.
 */
export interface ReconciliationReport {
  run_id: string;
  engine_version: string;
  schema_version: "1.0.0";
  config: Config;
  candidate_space: CandidateSpace;
  throughput: Throughput;
  cost: Cost;
  accuracy: Accuracy;
  /**
   * Full 4-arm ablation, or null when the run was executed with --fast (companion arms deliberately not computed).
   */
  ablation: Ablation | null;
  resolved: ResolvedMap;
  unresolved: UnresolvedMap;
  exceptions: ExceptionEntry[];
  closures: Closures;
  guardrail: Guardrail;
  controls: Controls;
}
export interface Config {
  seed: number;
  seed_set: SeedSet;
  n: number;
  mode: "rules_only" | "agent_only" | "rules_agent" | "random";
  model: string;
  /**
   * Which LLM backend actually produced this run's agent numbers: a live Anthropic call, the offline heuristic simulator, or none (mode never invoked an agent). Never omitted, never silently swapped.
   */
  agent_backend: "live" | "heuristic" | "none";
  temperature: number;
  prompt_hash: string;
  max_turns: number;
  concurrency: number;
  tolerances: {
    drift_paise: number;
    skew_days: number;
    pct_delta: number;
  };
  guardrail: {
    min_confidence: number;
    min_fields: number;
  };
}
export interface CandidateSpace {
  size: number;
  blocker_recall: MetricValue;
}
export interface MetricValue {
  value: number;
  numerator: number;
  denominator: number;
}
export interface Throughput {
  measurement_mode: MeasurementMode;
  runs_measured: number;
  wall_clock_seconds_median: number;
  rows_total: number;
  rows_per_second_end_to_end: MetricValue;
  residuals_per_second_agent_path: MetricValue;
  stage_seconds: {
    generate: number;
    block: number;
    match: number;
    agent: number;
    guardrail: number;
    classify: number;
    close: number;
    grade: number;
    report: number;
  };
  llm_calls: number;
  llm_retries: number;
  llm_p50_ms: number;
  llm_p95_ms: number;
  agent_turns: {
    mean: number;
    max: number;
    single_turn_fraction: number;
  };
}
export interface Cost {
  tokens_in: number;
  tokens_out: number;
  cache_hit_rate: number;
  cost_usd: number;
  cost_per_100_rows_usd: number;
  pricing_last_verified: string;
}
export interface Accuracy {
  match_rate: MetricValue;
  resolved_rate: MetricValue;
  unresolved_rate: MetricValue;
  links: {
    bank_payout: LinkMetrics;
    payout_ledger: LinkMetrics;
  };
}
export interface LinkMetrics {
  tp: number;
  fp: number;
  fn: number;
  tn: number;
  precision: MetricValue;
  recall: MetricValue;
  f1: number;
}
export interface Ablation {
  rules_only: AblationArm;
  agent_only: AblationArm;
  rules_agent: AblationArm;
  random: AblationArm;
  agent_lift: MetricValue;
  precision_cost: number;
}
export interface AblationArm {
  match_rate: number;
  precision: number;
  cost_usd: number;
}
export interface ResolvedMap {
  clean: number;
  drift: number;
  timing_tolerated: number;
  utr_recovered: number;
  refund: number;
}
export interface UnresolvedMap {
  amount_mismatch: number;
  fee_mismatch: number;
  timing_break: number;
  missing_utr: number;
  duplicate: number;
  refund_unpaired: number;
  orphan_bank: number;
  orphan_ledger: number;
  partial_group: number;
}
export interface ExceptionEntry {
  exception_id: string;
  row_ids: string[];
  bucket:
    | "amount_mismatch"
    | "fee_mismatch"
    | "timing_break"
    | "missing_utr"
    | "duplicate"
    | "refund_unpaired"
    | "orphan_bank"
    | "orphan_ledger"
    | "partial_group";
  severity: "low" | "medium" | "high";
  /**
   * @minItems 2
   */
  evidence: [string, string, ...string[]];
  proposed_action: string;
  status: "open" | "assigned" | "resolved" | "wont_fix";
  assignee?: string | null;
  resolution_note?: string | null;
}
export interface Closures {
  applied: number;
  dry_run: boolean;
  reversible: boolean;
  second_pass_new_closures: number;
  closure_rate: MetricValue;
}
export interface Guardrail {
  proposals: number;
  accepted: number;
  rejected: number;
  reject_reasons: {
    [k: string]: number;
  };
}
export interface Controls {
  shuffled_truth: {
    passed: boolean;
    observed_match_rate: number;
  };
  null_agent: {
    passed: boolean;
    identical_to_rules_only: boolean;
  };
  random_matcher: {
    passed: boolean;
    observed_precision: number;
    observed_match_rate: number;
  };
  poisoned_prompt: {
    passed: boolean;
    leak_detector_fired: boolean;
  };
  inverted_rule: {
    passed: boolean;
    tests_failed: number;
  };
  disabled_dedup: {
    passed: boolean;
    duplicate_bucket_size: number;
  };
}
